apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: order-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "order-service"
        dapr.io/app-port: "5001"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        dapr.io/enable-metrics: "false"
    spec:
      containers:
        - image: ghcr.io/santode/dapr-food-demo-order-service:4684e9506748a464694e006ea8fd2ca753b07b7e
          ports:
            - containerPort: 5001
              name: http1
          env:
            - name: DAPR_HTTP_PORT
              value: "3500"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kitchen-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "kitchen-service"
        dapr.io/app-port: "5002"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: ghcr.io/santode/dapr-food-demo-kitchen-service:4684e9506748a464694e006ea8fd2ca753b07b7e
          ports:
            - containerPort: 5002
              name: http1
          env:
            - name: DAPR_HTTP_PORT
              value: "3500"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bar-service
  namespace: default
spec:
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "bar-service"
        dapr.io/app-port: "5003"
        dapr.io/app-protocol: "http"
        dapr.io/config: "dapr-config"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: ghcr.io/santode/dapr-food-demo-bar-service:4684e9506748a464694e006ea8fd2ca753b07b7e
          ports:
            - containerPort: 5003
              name: http1
          env:
            - name: DAPR_HTTP_PORT
              value: "3500"
